### ISSUE TITLE
Geoviews Import Error 

### ISSUE THREAD

**Issue by CodeDC93** [ioam/geoviews#117]
Hello,
I'm running Python 3.6.3 via Conda and I can not import GeoViews into a notebook. I've successfully run "conda install -c conda-forge -c ioam holoviews geoviews" in command line. But whenever I go to a notebook to import GeoViews I get the error below. 

[1] Import GeoViews

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-11-bb2ce275a55a> in <module>()
----> 1 import geoviews

C:\Program Files\Anaconda3\lib\site-packages\geoviews\__init__.py in <module>()
      7 import param
      8 
----> 9 from .element import (_Element, Feature, Tiles,     # noqa (API import)
     10                       WMTS, LineContours, FilledContours, Text, Image,
     11                       Points, Path, Polygons, Shape, Dataset, RGB,

C:\Program Files\Anaconda3\lib\site-packages\geoviews\element\__init__.py in <module>()
      1 from holoviews.element import ElementConversion, Points as HvPoints
      2 
----> 3 from .geo import (_Element, Feature, Tiles, is_geographic,     # noqa (API import)
      4                   WMTS, Points, Image, Text, LineContours, RGB,
      5                   FilledContours, Path, Polygons, Shape, Dataset,

C:\Program Files\Anaconda3\lib\site-packages\geoviews\element\geo.py in <module>()
      3 from cartopy import crs as ccrs
      4 from cartopy.feature import Feature as cFeature
----> 5 from cartopy.io.img_tiles import GoogleTiles as cGoogleTiles
      6 from cartopy.io.shapereader import Reader
      7 from holoviews.core import Element2D, Dimension, Dataset as HvDataset, NdOverlay

C:\Program Files\Anaconda3\lib\site-packages\cartopy\io\img_tiles.py in <module>()
     30 from __future__ import (absolute_import, division, print_function)
     31 
---> 32 from PIL import Image
     33 import shapely.geometry as sgeom
     34 import numpy as np

C:\Program Files\Anaconda3\lib\site-packages\PIL\Image.py in <module>()
     56     # Also note that Image.core is not a publicly documented interface,
     57     # and should be considered private and subject to change.
---> 58     from . import _imaging as core
     59     if PILLOW_VERSION != getattr(core, 'PILLOW_VERSION', None):
     60         raise ImportError("The _imaging extension was built for another "

ImportError: DLL load failed: The specified module could not be found.

**Comment by philippjfr** [comment]
What version of ``PIL`` (or rather Pillow) do you have installed? Could you try something like:

``conda install -c conda-forge pillow=4.3.0``

I've seen issues like this on Windows before, could you confirm that's your current OS?

**Comment by CodeDC93** [comment]
I'm on Windows 7

**Comment by CodeDC93** [comment]
Ran  conda install -c conda-forge pillow=4.3.0 and the initial error is solved. However, a new import error occurs.  

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-bb2ce275a55a> in <module>()
----> 1 import geoviews

C:\Python\dev_env\SciPy_Stack\geoviews\geoviews\__init__.py in <module>()
      7 import param
      8 
----> 9 from .element import (_Element, Feature, Tiles,     # noqa (API import)
     10                       WMTS, LineContours, FilledContours, Text, Image,
     11                       Points, Path, Polygons, Shape, Dataset, RGB,

C:\Python\dev_env\SciPy_Stack\geoviews\geoviews\element\__init__.py in <module>()
      1 from holoviews.element import ElementConversion, Points as HvPoints
      2 
----> 3 from .geo import (_Element, Feature, Tiles, is_geographic,     # noqa (API import)
      4                   WMTS, Points, Image, Text, LineContours, RGB,
      5                   FilledContours, Path, Polygons, Shape, Dataset,

C:\Python\dev_env\SciPy_Stack\geoviews\geoviews\element\geo.py in <module>()
      7 from holoviews.core import Element2D, Dimension, Dataset as HvDataset, NdOverlay
      8 from holoviews.core.util import basestring, pd, max_extents, dimension_range
----> 9 from holoviews.element import (
     10     Contours as HvContours, Graph as HvGraph, Image as HvImage,
     11     Nodes as HvNodes, Path as HvPath, Polygons as HvPolygons,

ImportError: cannot import name 'TriMesh'

**Comment by philippjfr** [comment]
Great. That looks like you are installing GeoViews from master, which also requires HoloViews master. I'd recommend either install GeoViews 1.4.2 and HoloViews 1.9.2 or installing both from master.

**Comment by CodeDC93** [comment]
Hey I've run 
pip install GeoViews==1.4.2
pip install HoloViews==1.9.2
Holoviews imports fine version (1.9.2-x-g94abb1bdb). but "TriMesh" error still persist with GeoViews import .

**Comment by philippjfr** [comment]
You must have a local copy of GeoViews that's getting imported, I only merged the TriMesh thing a few days ago so it's definitely not in GeoViews 1.4.2.

**Comment by CodeDC93** [comment]
Thanks for all your help so far. Geoviews looks like really cool tool - can't wait to get it working.  So I ran 
pip uninstall GeoViews to remove any local versions, and re-installed with pip install git+https://github.com/ioam/geoviews.git - but that TriMesh error is still there in Jupyter Notebook

**Comment by CodeDC93** [comment]
Uninstalled( Conda Uninstall Geoviews) and reinstalled(conda install -c conda-forge -c ioam holoviews geoviews)  import still fails with TriMesh.

**Comment by philippjfr** [comment]
Very odd indeed. Could you provide the output of the following commands:

```python
import geoviews as gv
print(gv)
print(gv.__version__)
```

**Comment by CodeDC93** [comment]
import geoviews as gv
print(gv)
print(gv.__version__)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-0b65dc7b22a6> in <module>()
----> 1 import geoviews as gv
      2 print(gv)
      3 print(gv.__version__)

C:\Python\dev_env\SciPy_Stack\geoviews\geoviews\__init__.py in <module>()
      7 import param
      8 
----> 9 from .element import (_Element, Feature, Tiles,     # noqa (API import)
     10                       WMTS, LineContours, FilledContours, Text, Image,
     11                       Points, Path, Polygons, Shape, Dataset, RGB,

C:\Python\dev_env\SciPy_Stack\geoviews\geoviews\element\__init__.py in <module>()
      1 from holoviews.element import ElementConversion, Points as HvPoints
      2 
----> 3 from .geo import (_Element, Feature, Tiles, is_geographic,     # noqa (API import)
      4                   WMTS, Points, Image, Text, LineContours, RGB,
      5                   FilledContours, Path, Polygons, Shape, Dataset,

C:\Python\dev_env\SciPy_Stack\geoviews\geoviews\element\geo.py in <module>()
      7 from holoviews.core import Element2D, Dimension, Dataset as HvDataset, NdOverlay
      8 from holoviews.core.util import basestring, pd, max_extents, dimension_range
----> 9 from holoviews.element import (
     10     Contours as HvContours, Graph as HvGraph, Image as HvImage,
     11     Nodes as HvNodes, Path as HvPath, Polygons as HvPolygons,

ImportError: cannot import name 'TriMesh'

**Comment by philippjfr** [comment]
Oh, I'm an idiot, that was to be expected. It looks like I was right though, it's grabbing GeoViews from here: ``C:\Python\dev_env\SciPy_Stack\geoviews\geoviews\element\geo.py`` not from your environment. Try deleting that copy and then installing GeoViews using conda again.

**Comment by jbednar** [comment]
From the error messages, it looks to me like the initial errors were from a conda installation ("C:\Program Files\Anaconda3\lib\site-packages\geoviews\"), but the new ones are from some other installation (C:\Python\dev_env\SciPy_Stack\geoviews\geoviews). So I don't think the conda install commands you listed are relevant for these error messages.  Maybe try uninstalling *all* versions until geoviews is just not importable and try again.

**Comment by CodeDC93** [comment]
![geoviews](https://user-images.githubusercontent.com/17088020/34685466-691d4ad0-f476-11e7-9bfb-1cb03777e688.JPG)

**Comment by philippjfr** [comment]
Sorry, fixed it just not, missed a ``-c``:

```
conda install -c ioam -c conda-forge geoviews
```

**Comment by CodeDC93** [comment]
![geoviews2](https://user-images.githubusercontent.com/17088020/34686096-8d4ab170-f478-11e7-91fa-c37095aaf9c5.JPG)
 

![geoview_notebook](https://user-images.githubusercontent.com/17088020/34686147-b8a1d4f2-f478-11e7-9829-b935d13c6024.JPG)

**Comment by philippjfr** [comment]
It's still getting it from your old location. Ensure you're not running the notebook in ``C:\Python\dev_env\SciPy_Stack\geoviews\`` and probably just delete that repo entirely.

**Comment by philippjfr** [comment]
Probably also run ``pip uninstall holoviews``, this is where your troubles started ``pip install git+https://github.com/ioam/geoviews.git``.

**Comment by CodeDC93** [comment]
![geoviews_run](https://user-images.githubusercontent.com/17088020/34686735-81a020f6-f47a-11e7-98cb-34d94ebe06aa.JPG)

**Comment by philippjfr** [comment]
Yay, finally! Also thanks a lot for reporting this, we'll make sure to pin a working version of pillow so others don't run into this.

**Comment by CodeDC93** [comment]
Today GeoViews ... Tomorrow The World :globe_with_meridians:

**Comment by Sieboldianus** [comment]
About a year later, this still affects me on Windows computers. The proposed solution (`conda install -c conda-forge pillow=4.3.0`) also doesn't seem to work anymore. According to this [issue](https://github.com/python-pillow/Pillow/issues/2945) the current solution is:

```bash
conda install --channel conda-forge pillow=5.2.0
```
