### ISSUE TITLE
gv.WMTS not tiling correctly on zoom

### ISSUE THREAD

**Issue by kcpevey** [ioam/geoviews#159]
I'm using `gv.WMTS('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{X}/{Y}')`
to load a map with World Imagery tiles, it looks good on the initial load. However, when I zoom in, incorrect map tiles begin to appear as some of the tiles. It appears to be consistent each time I zoom in the same location. I used other map servers and didn't have to specify any additional information, so I'm not sure what I'm missing here?  
  
Here is an accurate image:  
![tile1](https://user-images.githubusercontent.com/15659110/39595956-9a1c559e-4ed6-11e8-8a6c-4535a41d3c6f.PNG)  
Then the next zoom level:  
![tile2](https://user-images.githubusercontent.com/15659110/39595960-9cb4f216-4ed6-11e8-8822-4297e5d26e10.PNG)

**Comment by philippjfr** [comment]
I suspect two of the parameters (presumably X and Y) are switched around, try:

``gv.WMTS('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{Y}/{X}')``
