### ISSUE TITLE
Consider not using shell commands in notebooks and stick to python

### ISSUE THREAD

**Issue by ceball** [ioam/geoviews#166]
E.g. in https://github.com/ioam/geoviews/blob/master/examples/Colocated_cube_pair.ipynb there's `ls -lh files/*.pp`. That's not going to work on windows for most people (e.g. won't work if using Anaconda Prompt), although at first glance it seems like it might work (there is an `ls` alias from ipython).

![untitled](https://user-images.githubusercontent.com/1929/39827349-9e5e5b06-53af-11e8-9222-37f2f903d272.png)

I'm not sure if those aliases help most people or just lead to confusion; I can't tell (although I've personally only seen confused people...although I think *I* am not confused, but maybe I am!).

A general argument against using them could be: why not stick to python where possible instead of introducing a new thing?

**Comment by philippjfr** [comment]
That notebook should be deleted.

**Comment by jbednar** [comment]
Yes, we should remove anything not crossplatform that we find.

**Comment by philippjfr** [comment]
I've deleted these notebooks, they're pretty outdated.

**Comment by ceball** [comment]
I might be confused, but at least https://github.com/ioam/geoviews/blob/master/examples/Colocated_cube_pair.ipynb still seems to be present...

**Comment by philippjfr** [comment]
That's because I hadn't pushed :-)
