### ISSUE TITLE
Update geoviews on conda-forge

### ISSUE THREAD

**Issue by ceball** [ioam/geoviews#182]
I think we're waiting for 1.5.1 to do this, but the dependencies need to be updated, entry points added, and at least some tests run.

I can make PRs from https://github.com/conda-forge/staged-recipes/compare/master...ceball:add_geoviews-core?expand=1 and https://github.com/conda-forge/geoviews-feedstock/compare/master...ceball:update_dependencies?expand=1 when the time comes.

**Comment by philippjfr** [comment]
I released 1.5.1 this afternoon, so we should go ahead with this.

**Comment by ceball** [comment]
I've made https://github.com/conda-forge/staged-recipes/pull/6042 and https://github.com/conda-forge/geoviews-feedstock/pull/4

I've closed this issue as we can discuss isses on those PRs (maybe you could check them, @philippjfr...).
