### ISSUE TITLE
Find a way to allow groupby and .to on Geopandas dataset

### ISSUE THREAD

**Issue by philippjfr** [ioam/geoviews#184]
Currently when declaring a geopandas dataset HoloViews does not know about the implicit variables which refer to the coordinates inside the geometry column which means that the validation fails during the groupby operation.

**Comment by jbednar** [comment]
I may easily have gotten confused, but I'm not sure all the corresponding elements are present as methods for `.to` for GeoPandas dataframes; e.g. is there a `.to.polygons`?  Seems like something that could be addressed at the same time.
