### ISSUE TITLE
Broken aspect in a Dynamic map

### ISSUE THREAD

**Issue by bjlittle** [ioam/geoviews#19]
Given a single surface_temperature map called `frame`, the following DynamicMap definition has a very strange aspect and doesn't seem to be working right.

``` python
surface_temp = iris.load_cube(iris.sample_data_path('GloSea4', 'ensemble_001.pp'))
frame = hv.Dataset(surface_temp).groupby(['time'], group_type=gv.Image).last

def callback(latitude, longitude):
    return frame * hv.HLine(latitude) * hv.VLine(longitude)

hv.DynamicMap(callback, kdims=[hv.Dimension('latitude', range=(-90.0,90.0)), 
                               hv.Dimension('longitude', range=(-150.0, 150.0))])
```

It looks fine if you only look at a single overlay.

**Comment by philippjfr** [comment]
VLine and HLine are not geographic Elements and really not be overlaid onto a geographic plot, if you need them we should implement geographic equivalents for them. Certainly possible that there is another issue here though.

**Comment by jlstevens** [comment]
I was about to close this issue and open a new one suggesting projection-aware VLine/HLine. Based on your comment maybe this isn't possible?

@marqh Any idea how this would be done? I've been discussing the idea of using sliders to move a crosshair around but for that we need to draw vlines/hlines.

**Comment by philippjfr** [comment]
The axvline and axhline plotting calls do accept a transform, so might well work fine.

**Comment by philippjfr** [comment]
I tried implementing VLine and HLine with axvline and axhline but it doesn't like a transform argument. So I'm still not sure how best to implement a coordinate reference system aware HLine and VLine yet.

**Comment by philippjfr** [comment]
This seems to work fine with current holoviews and geoviews master.

<img width="883" alt="screen shot 2017-02-11 at 4 43 54 am" src="https://cloud.githubusercontent.com/assets/1550771/22851279/c18f7128-f014-11e6-94f0-e1ba399e282b.png">
