### ISSUE TITLE
LICENSE file is out of date?

### ISSUE THREAD

**Issue by ceball** [ioam/geoviews#190]
Making this issue just because c-f requires the LICENSE file for the geoviews metapackage on conda-forge (https://github.com/conda-forge/geoviews-feedstock/pull/4), so I happened to notice in the diff:
  * copyright holder is `geoviews` but who/what is `cube-explorer`?
  * copyright years out of date

I have absolutely no idea (or opinion) about what any of it should be, or whether it matters.

**Comment by philippjfr** [comment]
Fixed in 94592359af26a7d93456ea3cd41041026b23e2bf
