### ISSUE TITLE
FutureWarning: from_items is deprecated

### ISSUE THREAD

**Issue by rsignell-usgs** [ioam/geoviews#195]
I'm getting this warning when using holoviews and geoviews from conda-forge:
```
/opt/conda/lib/python3.6/site-packages/holoviews/core/data/pandas.py:130: FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.
  zip(columns, data)])
```
![2018-06-26_6-51-11](https://user-images.githubusercontent.com/1872600/41907698-a7b54022-790f-11e8-9a93-daef8bfa4a90.png)

**Comment by philippjfr** [comment]
Thanks, this was fixed in https://github.com/ioam/holoviews/commit/8aafda99a27a3cba9c11b849ed60bcd6ed38e321, which was included in the HoloViews 1.10.5 release. As far as I can tell that is already available on conda-forge.
