### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by DamienIrving** [ioam/geoviews#31]
I'm trying to install geoviews on a linux machine. I created a new conda environment to try it out and ran the following commands successfully:

```
conda create --name geoviews jupyter
conda install -c scitools/label/dev -c conda-forge iris cartopy
conda install xarray
conda install -c ioam holoviews
```

However when trying to install geoviews I found a problem:

```
conda install -c ioam geoviews
Fetching package metadata: ......
Solving package specifications: ....................................................
Error: Could not find some dependencies for geoviews: cartopy
```

I can confirm that cartopy is installed:

```
conda list
...
cartopy                   0.14.2              np111py27_1    conda-forge
...
```

so I'm not sure what the problem is?

**Comment by philippjfr** [comment]
I'll look into this later today. Could you tell me what platform you're on?

**Comment by mcmorgan27** [comment]
I'm having a similar problem.  I'm on ubuntu 16.04 LTS.

**Comment by philippjfr** [comment]
I think this is down to incomplete instructions. Did you activate the environment after creating it? Could you try doing:

```bash
conda create --name geoviews jupyter
**source activate geoviews**
conda install -c scitools/label/dev -c conda-forge iris cartopy
conda install xarray
conda install -c ioam holoviews geoviews
```

**Comment by philippjfr** [comment]
I'll try to dig up an Ubuntu machine to confirm it's actually working, working fine on OSX for me at least.

**Comment by mcmorgan27** [comment]
edited trace:

conda create --name geoviews jupyter

<snip>  lot's of packages listed </snip>

source activate geoviews
discarding /home/mcmorgan/anaconda3/bin from PATH
prepending /home/mcmorgan/anaconda3/envs/geoviews/bin to PATH
(geoviews)mcmorgan@feynman:~/projects$ conda install -c scitools/label/dev
-c conda-forge iris cartopy

<snip>  more packages to install </snip>

(geoviews)mcmorgan@feynman:~/projects$ conda list
# packages in environment at /home/mcmorgan/anaconda3/envs/geoviews:
...
cartopy                   0.14.2              np111py35_1    conda-forge
...

(geoviews)mcmorgan@feynman:~/projects$ conda install xarray

Linking packages ...
[      COMPLETE      ]

(geoviews)mcmorgan@feynman:~/projects$ conda install -c ioam holoviews
geoviews
Fetching package metadata: ......
Solving package specifications:
................................................................
Error: Could not find some dependencies for geoviews: cartopy

Did you mean one of these?

    geoviews, holoviews

Did you mean one of these?

    astropy

You can search for this package on anaconda.org with

    anaconda search -t conda cartopy

 (and similarly for the other packages)


- mcm

**Comment by philippjfr** [comment]
Okay, just managed to replicate this I still have no good idea why this happens and will follow up with the conda team, but I was able to solve it by installing them all in one go:

```bash
conda create --name geoviews jupyter xarray
source activate geoviews
conda install -c scitools/label/dev -c conda-forge -c ioam holoviews geoviews iris cartopy
```

**Comment by mcmorgan27** [comment]
I'll give it a shot.  It works on py27 i assume?

**Comment by philippjfr** [comment]
>I'll give it a shot.  It works on py27 i assume?

Yes, Python 2.7, 3.4 and 3.5 should work.

**Comment by mcmorgan27** [comment]
all in one go seems to work for me.

Thanks!

- mcm

**Comment by philippjfr** [comment]
Great, if you have any other questions we're also available on [Gitter](gitter.im/ioam/holoviews). @DamienIrving let me know if this fixes the issue for you as well. I've already updated the installation instructions in the readme.

**Comment by DamienIrving** [comment]
@philippjfr Yep, installing it all in one go worked for me too.

Also, thanks for the Gitter link (will ask questions there in future) and congrats on a fantastic library!

**Comment by khannaum** [comment]
on windows 64 bit i install  i apply the following commands

conda create --name geoviews jupyter xarray
source activate geoviews
conda install -c scitools/label/dev -c conda-forge -c ioam holoviews geoviews iris cartopy

(geoviews) D:\Anaconda\envs\geoviews>python.exe
Python 2.7.12 | packaged by conda-forge | (default, Sep  8 2016, 14:46:05) [MSC
v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import geoviews
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda\envs\geoviews\lib\site-packages\geoviews\__init__.py", line
9, in <module>
    from .element import (_Element, Feature, Tiles,     # noqa (API import)
  File "D:\Anaconda\envs\geoviews\lib\site-packages\geoviews\element\__init__.py
", line 3, in <module>
    from .geo import (_Element, Feature, Tiles, is_geographic,     # noqa (API i
mport)
  File "D:\Anaconda\envs\geoviews\lib\site-packages\geoviews\element\geo.py", li
ne 9, in <module>
    from holoviews.element import (Text as HVText, Path as HVPath,
**ImportError: cannot import name GridImage**

Kindly help.

**Comment by jbednar** [comment]
@philippjfr:

> conda create --name geoviews jupyter xarray
> source activate geoviews
> conda install -c scitools/label/dev -c conda-forge -c ioam holoviews geoviews iris cartopy

Doesn't conda go through the channels in order left to right?  If so, shouldn't ioam precede conda-forge, to avoid getting the old version of holoviews that's on conda-forge?  I would have thought it should be:

```
conda create --name geoviews jupyter xarray
source activate geoviews
conda install -c ioam -c scitools/label/dev -c conda-forge holoviews geoviews iris cartopy
```

@khannaum, does that work any better?

**Comment by philippjfr** [comment]
@jbednar Yes, you're right, I'll fix the README again.

**Comment by jbednar** [comment]
For what it's worth, here are the versions of each of those packages that are installed on my own system, which I think is what you should see with the above command:

```
iris                      1.10.dev1                py27_0    scitools/label/dev
geoviews                  1.1.0                    py27_0    ioam
holoviews                 1.6.2                    py27_0    ioam
cartopy                   0.14.2              np110py27_1    conda-forge
```

**Comment by philippjfr** [comment]
The latest instructions should work:

```
conda install -c conda-forge -c ioam holoviews geoviews
# (Optional)
conda install xarray
conda install -c conda-forge iris
```
