### ISSUE TITLE
holoviews.element.raster.GridImage class missing

### ISSUE THREAD

**Issue by dalepartridge** [ioam/geoviews#32]
The installation seemed to be fine, but when I import the code I get an import error related to GridImage in the initialization line:

`from holoviews.element import (Text as HVText, Path as HVPath, Polygons as HVPolygons, GridImage)`

Looking in the holoview package under element/raster.py, where GridImage is supposed to be (according to [http://dev.holoviews.org/Reference_Manual/holoviews.element.html](url)), there is no GridImage class. All the other classes from the link that are supposed to be there are present. Not sure why this bit of code is missing.

**Comment by v0lat1le** [comment]
Just had the same issue... Turned out my holoviews came from conda-forge channel which has an outdated version (1.5.0). Doing `conda update -c ioam holoviews -n env` seemed to solve this.

**Comment by philippjfr** [comment]
Thanks for the quick response @v0lat1le . Yes, we currently depend on the holoviews version from our privately managed ``ioam`` channel, we're in contact with the conda team to get the main channel updated asap.

**Comment by dalepartridge** [comment]
Thanks, that did the trick.
