### ISSUE TITLE
on windows 64 bit 

### ISSUE THREAD

**Issue by khannaum** [ioam/geoviews#34]
on windows 64 bit i install i apply the following commands

conda create --name geoviews jupyter xarray
source activate geoviews
conda install -c scitools/label/dev -c conda-forge -c ioam holoviews geoviews iris cartopy

(geoviews) D:\Anaconda\envs\geoviews>python.exe
Python 2.7.12 | packaged by conda-forge | (default, Sep 8 2016, 14:46:05) [MSC
v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

import geoviews
Traceback (most recent call last):
File "", line 1, in 
File "D:\Anaconda\envs\geoviews\lib\site-packages\geoviews__init__.py", line
9, in 
from .element import (Element, Feature, Tiles, # noqa (API import)
File "D:\Anaconda\envs\geoviews\lib\site-packages\geoviews\element__init_.py
", line 3, in 
from .geo import (_Element, Feature, Tiles, is_geographic, # noqa (API i
mport)
File "D:\Anaconda\envs\geoviews\lib\site-packages\geoviews\element\geo.py", li
ne 9, in 
from holoviews.element import (Text as HVText, Path as HVPath,
ImportError: cannot import name GridImage
Kindly help.

**Comment by hansbrenna** [comment]
I have the same issue on Ubuntu 16.04 using python 2.7. I did
```
conda install -c scitools/label/dev -c conda-forge iris cartopy
conda install -c conda-forge -c ioam holoviews geoviews
```
to install and when I try to import geoviews, either alone or using
```
import numpy as np
import xarray as xr
import pandas as pd
import holoviews as hv
import geoviews as gv
import iris
import cartopy

from cartopy import crs
from cartopy import feature as cf
from geoviews import feature as gf
```
I get the same error message.

**Comment by philippjfr** [comment]
It seems the install instructions still aren't quite right. I'll make sure to pin the holoviews version in future but for now you should be able to get the correct version with:

```
conda install -c ioam holoviews=1.6.2
```
