### ISSUE TITLE
Question-asking location

### ISSUE THREAD

**Issue by kthyng** [ioam/geoviews#35]
Hi. I am excited about the possibility of using geoviews to display some analysis of mine for a project. I am doing my best to follow the [examples](https://www.continuum.io/blog/developer-blog/introducing-geoviews) but am meeting a lot of walls. Where might I go to have a conversation about how to use this tool?
Thanks for the great work!
Kristen

**Comment by philippjfr** [comment]
Hi @kthyng, thanks first of all. We're very happy hear your feedback to perhaps make things clearer for new users and are always happy to answer question in our [Gitter channel](https://gitter.im/ioam/holoviews).

**Comment by kthyng** [comment]
Ok I moved there, thanks.
