### ISSUE TITLE
Lat/lon labels

### ISSUE THREAD

**Issue by kthyng** [ioam/geoviews#36]
It'd be great to have the labels on maps x and y axis show latitude/longitude (that is, in degrees), instead of (when using Bokeh, for example), in the meters of the underlying Mercator projection.

So instead of something labeled like the following, with meters for units:
<img width="423" alt="screen shot 2016-09-11 at 8 09 34 am" src="https://cloud.githubusercontent.com/assets/3487237/18417476/378ae600-77f7-11e6-8bfd-a4ce043f6b12.png">

I would want something labeled like the following, with degrees labeled, and the ability to make it look nicely formatted (not that these are in the same area of the world):
<img width="504" alt="screen shot 2016-09-11 at 8 09 14 am" src="https://cloud.githubusercontent.com/assets/3487237/18417478/3df54e72-77f7-11e6-90d0-dde2b461a0d8.png">

I made the second plot with `cartopy` and used some of their extra stuff with `matplotlib` to get the labels formatted nicely.

In my experience, this would be following convention set up by, for example, the `basemap` package.

Thanks!

**Comment by philippjfr** [comment]
Adding nice tick formatting for mercator coordinates will be supported in bokeh very soon: https://github.com/bokeh/bokeh/pull/6017. We should make use of it for all geographic bokeh plots.

**Comment by philippjfr** [comment]
This has finally been implemented, closing.

**Comment by zxdawn** [comment]
@philippjfr The formatter doesn't work well. As you can see in the `Tick formatters` section of this [tutorial](http://holoviews.org/user_guide/Customizing_Plots.html).:
```
def formatter(value):
    return str(value) + ' days'

curve.relabel('Tick formatters').opts(xformatter=formatter, yformatter='$%.2f', width=500)
```
![image](https://user-images.githubusercontent.com/30388627/60635395-42133d80-9e45-11e9-98b5-097fe891c421.png)

But the xaxis ticks still keep same. So, I want to get the degree symbol on ticks like @kthyng said before, how to add it?
