### ISSUE TITLE
Add gv.help and link to holoviews docs more prominently

### ISSUE THREAD

**Issue by ktyle** [ioam/geoviews#42]
Hi, could someone point out some documentation so as to how I could customize the call to gv.LineContours and gv.FilledContours (i.e., specify contour levels, color, etc.) ?  Thanks!

**Comment by philippjfr** [comment]
@ktyle It's probably best to start with some of the basic [HoloViews Tutorials](holoviews.org/Tutorials/), specifically have a look at the [Options Tutorial](http://holoviews.org/Tutorials/Options.html).

The short of it is that there are three kinds of options ``style``, ``plot`` and ``norm`` options. You can find out about the supported options using ``holoviews.help`` (I will add gv.help to mirror the holoviews version):

```python
import holoviews as hv
hv.help(gv.FilledContours)
```

```
Curve
...
Help for the data object: holoviews.help(Curve) or holoviews.help(<curve_instance>)

-------------
Style Options
-------------

	alpha, c, color, linestyle, linewidth, ls, lw, marker, visible

(Consult matplotlib's documentation for more information.)

------------
Plot Options
------------
...
```

In the notebooks those you can use the ``%%opts`` magic to apply options by specifying the name of the element and the options by putting plot options in square brackets (``[ ]``) and style options in braces (``( )``):

```python
%%opts FilledContours [levels=[0.1, 0.5, 0.75, 1]] (cmap='viridis')
gv.FilledContours({'x': range(10), 'y': range(10), 'z': np.random.rand(10,10)},
                  kdims=['x','y'], vdims=['z'])
```

Note that both the Element names and the options tab complete once you've typed %%opts and opened either the square brackets or braces.

![opts](https://cloud.githubusercontent.com/assets/1550771/20078662/739e368c-a539-11e6-9e79-5bd8feac81bc.gif)

In pure python you can apply options by calling the element like this:

```python
contours =gv.FilledContours({'x': range(10), 'y': range(10), 'z': np.random.rand(10,10)},
            kdims=['x','y'], vdims=['z'])
styled = contours(plot={'levels': [0.1, 0.5, 0.75, 1]}, style={'cmap':'viridis'})
hv.Store.renderers['matplotlib'].save(styled, 'styled_contours')
```

**Comment by philippjfr** [comment]
I'm going to repurpose this issue to make sure I add ``gv.help`` and link to HoloViews tutorial more prominently.
