### ISSUE TITLE
Add basemap to the bokeh EU Referendum example?

### ISSUE THREAD

**Issue by Yafei777** [ioam/geoviews#43]
Hi, I am new and trying to apply geoviews to my project.

Is it possible to add a basemap tile to the [Bokeh 'EU Referendum' example notebook](http://geo.holoviews.org/Working_with_Bokeh.html)?

I've tried simply ' * ' a base map tile and a bokeh map, like this:

```
bokeh_map = gv.Shape.from_records(shapes.records(), hv_data, on='ID', value='POP',
                     index=['ID'], crs=ccrs.PlateCarree()))
base_map = gv.WMTS(WMTSTileSource(url='http://c.tile.openstreetmap.org/{Z}/{X}/{Y}.png'), 
                     crs=ccrs.PlateCarree())
bokeh_map * base_map

```

and then I got an error:

```
TypeError: 'odict_values' object does not support indexing
```

as well as the output:

```
:Overlay
   .NdOverlay.Area :NdOverlay   [CLASS_ID]
      :Shape   [Longitude,Latitude]   (AREA)
   .WMTS.I         :WMTS   [Longitude,Latitude]
```

Thanks for any hint!

**Comment by philippjfr** [comment]
Sounds like a python3 issue, will investigate later today.

**Comment by jbednar** [comment]
Apart from a bunch of warnings, this seems to work fine now in both Python 2 and in Python 3 (shown here): 

![image](https://cloud.githubusercontent.com/assets/1695496/21809578/fd45e000-d70d-11e6-94ca-47961dedc621.png)

That's using the latest master of both holoviews and geoviews; the previous releases showed the error above.  Seems fixed.
