### ISSUE TITLE
Bad link in documentation

### ISSUE THREAD

**Issue by andreas-h** [ioam/geoviews#52]
In the [Working with Bokeh](http://geo.holoviews.org/Working_with_Bokeh.html) Tutorial on the website, the link "The tutorial on Geometries" (first sentence of the "Chloropleths" section) is broken; it points to the .ipynb file (prompting a download) instead of the rendered HTML version.

**Comment by philippjfr** [comment]
Thanks for reporting this, we had a script that's meant to replace the ipynb links with html links on the built website, but it seems it wasn't run on the current build.

**Comment by philippjfr** [comment]
Thanks for having reported this, it's fixed in the latest website build.
