### ISSUE TITLE
problems with geoviews bokeh backend

### ISSUE THREAD

**Issue by jsboyle** [ioam/geoviews#54]
I was trying to work through the geoviews bokeh backend examples (http://geo.holoviews.org/Working_with_Bokeh.html)

The "WMTS Tile Sources" example fails with:
AttributeError:'TileRenderer' object has no attribute 'set'

The "Plotting Data " example fails with:
AttributeError: 'Figure' object has no attribute 'set'

I have a python3.6 Anaconda distribution (with bokeh 0.12.4) , and installed geoviews 1.2.0dev1, holoviews 1.6.2  using conda. On a machine running macOS 10.12.3.
Note that although the conda install was for geoviews 1.2.0dev1, the __version__ yields 1.1.0.
I can provide more complete tracebacks (they are lengthy) if needed.

I am at a loss, there appears to be some problem in invoking bokeh.

**Comment by philippjfr** [comment]
See https://github.com/ioam/geoviews/issues/49, hopefully we'll have a 1.7 release by the end of next week.

**Comment by philippjfr** [comment]
Both holoviews 1.7.0 and geoviews 1.2.0 have been released so this should now be fixed. Please reopen if you encounter any issues.
