### ISSUE TITLE
Scale of NaturalEarthFeature is ignored (always plotting coarse)

### ISSUE THREAD

**Issue by andreas-h** [ioam/geoviews#56]
Using Geoviews 1.1.0, I have the problem that the scale of any NaturalEarthFeature from cartopy seems to be ignored. 

    from cartopy.feature import NaturalEarthFeature
    import cartopy.crs as ccrs
    import matplotlib.pyplot as plt
    %matplotlib inline
    import holoviews as hv
    import geoviews as gv
    hv.notebook_extension()
    import xarray as xr

I am using the sample data file from https://github.com/SciTools/iris-sample-data/blob/master/iris_sample_data/sample_data/E1_north_america.nc?raw=true

    ds = xr.open_dataset('E1_north_america.nc')
    arr = ds['air_temperature'][0]
    gvds = gv.Dataset(
            arr.to_dataset(), kdims=['longitude', 'latitude'],
            vdims=['air_temperature'])

I define a function to return the correct coastline feature for a given scale, just to be sure to use the same objects in both matplotlib and geoviews cases:

    def coastline(scale):
        return NaturalEarthFeature(
                category='physical', name='coastline', scale=scale,
                edgecolor='black', facecolor='none')

Using pure matplotlib, everything works as expected:

    fig, axs = plt.subplots(
            figsize=(8, 15), nrows=3,
            subplot_kw=dict(projection=ccrs.PlateCarree()))
    
    for ax, scale in zip(axs, ['10m', '50m', '110m']):
        arr.plot.pcolormesh(ax=ax, x='longitude', y='latitude', 
                        transform=ccrs.PlateCarree())
        ax.add_feature(coastline(scale))
        ax.set_title('Scale: {}'.format(scale))

![img_matplotlib](https://cloud.githubusercontent.com/assets/358378/24244852/df24c4b0-0fc0-11e7-96fb-ebdeabb955d0.png)

However, when using Geoviews, it seems like always the `110m` scale is displayed, even though I'm using a higher resolution feature:

    %%output backend='matplotlib' size=450
    
    def create_overlay(ds, scale):
        return hv.Overlay([
                ds.to(gv.Image, ['longitude', 'latitude']).relabel(scale),
                gv.Feature(coastline(scale)),
                ]).collate()
    
    plots = [create_overlay(gvds, sc) for sc in ['10m', '50m', '110m']]
    hv.Layout(plots).cols(1)

![img_geoviews](https://cloud.githubusercontent.com/assets/358378/24244863/e8fcf5c0-0fc0-11e7-9f85-ebd7c58bf37d.png)

**Comment by philippjfr** [comment]
You can control the scale of a feature by setting it as a plot option, e.g.

```python
img = ds.to(gv.Image, ['longitude', 'latitude']).relabel(scale)
hv.Layout([img*gv.feature.coastline(plot=dict(scale=scale)) for scale in ['10m', '50m', '110m']])
```

**Comment by andreas-h** [comment]
Thanks! It would be helpful if this were mentioned in the documentation; especially at http://geo.holoviews.org/Geometries.html you have an example where you load the graticules from NaturalEarth and set the scale there (and not when plotting).

When doing it like you mention (which works fine), how do I control the linewidth of the coastline (without the `%%opts` magic)?  Doing `gv.feature.coastline(plot=dict(scale=scale, linewidth=1.5))` doesn't work for me (ValueError in line 148 of holoviews/ipython/display_hooks.pyc).

**Comment by philippjfr** [comment]
>Thanks! It would be helpful if this were mentioned in the documentation; especially at http://geo.holoviews.org/Geometries.html you have an example where you load the graticules from NaturalEarth and set the scale there (and not when plotting).

Agreed.

>When doing it like you mention (which works fine), how do I control the linewidth of the coastline (without the %%opts magic)? Doing gv.feature.coastline(plot=dict(scale=scale, linewidth=1.5)) doesn't work for me (ValueError in line 148 of holoviews/ipython/display_hooks.pyc).

Have a look at the HoloViews [Options Tutorial](http://holoviews.org/Tutorials/Options.html), basically we make a distinction between plot and style options, so what you want to do in this case is this:

``gv.feature.coastline(plot=dict(scale=scale), style=dict(linewidth=1.5))``

**Comment by andreas-h** [comment]
Wonderful, works like a charm -- thanks a lot!

**Comment by poplarShift** [comment]
I've just been stumbling over the same issue. The first example of http://geo.holoviews.org/Geometries.html about `Feature`s still leads one to believe that selecting a different `scale` in the call to cartopy's NaturalEarthFeature should change anything.

Now I wonder whether this is related to #254 @philippjfr ?
