### ISSUE TITLE
Export Grid data to geotif

### ISSUE THREAD

**Issue by apiszcz** [ioam/geoviews#68]
Is there a capability or possible approach to export the data set to a Geotif file?
Thank.

**Comment by philippjfr** [comment]
@apiszcz Could you clarify? Do you mean exporting image data to geotiff or an actual plot? This may be something that's better handled by xarray.

**Comment by apiszcz** [comment]
Export to GEOTIFF.
Ideally one could 'render' to GEOTIFF or screen, etc.

**Comment by jbednar** [comment]
Sounds like you want to take a GeoViews object and export it as GeoTIFF, which is different from the "rendering" that HoloViews does using matplotlib or bokeh to create image files, but I suppose it is analogous (using the data plus the metadata to generate a viewable object).  I'd guess your best bet is to just get the data into a form that rasterio supports, then use rasterio to make the GeoTIFF.  Not sure how much work that is; if it's trivial, probably don't need to add any support in GeoViews for that; if it's complicated, not sure where that complicated code would go.  Some background:

https://github.com/pydata/xarray/issues/790

**Comment by apiszcz** [comment]
For now, I worked another path with rasterio.
