### ISSUE TITLE
Geoviews output

### ISSUE THREAD

**Issue by dtelliott79** [ioam/geoviews#70]
I have a choropleth map with hover text that I was able to create using Geoviews. Great job, by the way! I don't think I could have made the plot as I envisioned without your software!

Right now, I process the data and render the plot in a Jupyter notebook. I do not think that my issue represents a bug in the software, but I've been searching, trying suggestions I find, waiting (since GeoViews is quite new), and searching again for well over a month now, and I thought I would give this medium a try:

I want to take the plot I've made and save it as stand alone HTML (without Python code). Further, I want it to display in Internet Explorer. It currently displays fine in Chrome, but IE gives a blank page (see attached).

Thanks for any pointers you can give!

[Untitled1.zip](https://github.com/ioam/geoviews/files/1046135/Untitled1.zip)

**Comment by philippjfr** [comment]
So I apologize I completely missed this. I'm afraid it's not quite clear to me why this doesn't work in IE, but it is probably an issue in bokeh, that I think might be resolved now. If you do have the time to come back to this it would be great if you could confirm if this issue still occurs with bokeh 0.12.13. For now I'll close the issue.
