### ISSUE TITLE
Dashboard_Demo - cannot import name 'NbParams'

### ISSUE THREAD

**Issue by epifanio** [ioam/geoviews#80]
Trying to run the [Dashboard_Demo notebook](https://github.com/ioam/geoviews/blob/master/notebooks/Dashboard_Demo.ipynb) :  

```
from paramnb import NbParams, FileSelector
```
returns:
```
ImportError: cannot import name 'NbParams'
```

paramnb version: 2.0.2

**Comment by jbednar** [comment]
Thanks!  That example was written for an earlier pre-release version of ParamNB, and it clearly needs updating for to match the released version.  I believe NbParams is what is now called Widgets, but there are probably other changes needed to.

**Comment by philippjfr** [comment]
Notebook now, updated.
