### ISSUE TITLE
Kernel dies when running example notebooks

### ISSUE THREAD

**Issue by duncanwp** [ioam/geoviews#85]
I'm just getting to grips with geoviews and it looks really helpful but many of the example notebooks break when I try to run them. 

Specifically in the 'working_with_Bokeh.ipynb' notebook when running the third cell the kernel dies and logs the following error:
`Assertion failed: (0 != cs), function GEOSCoordSeq_getSize_r, file geos_ts_c.cpp, line 3797.`

I'm guessing this is an incompatible GEOS issue, but I just did a clean install from the condo-forge and ioam conda channels. I've attached my environment setup in [geoviews_env.txt](https://github.com/ioam/geoviews/files/1280552/geoviews_env.txt). Any thoughts appreciated.

**Comment by philippjfr** [comment]
Sorry I never replied to this. The issue is likely a incompatible system wide installation of libgeos interfering with the environment.

**Comment by duncanwp** [comment]
Yes, it seems to be due to https://github.com/SciTools/cartopy/issues/738 and associated issues - thanks!
