### ISSUE TITLE
Coordinate offset with WMTS

### ISSUE THREAD

**Issue by rr5577** [ioam/geoviews#95]
I tried to put a point (and subsequently a raster) over a wmts basemap, but can´t get it into the correct place.

The wmts is WebMercator (epsg 3857)
The point coordinates taken directly from the basemap.at viewer:
![image](https://user-images.githubusercontent.com/31547476/31884480-68426f16-b7ed-11e7-8370-6ed47c108dd5.png)

```
%%output backend='bokeh'
%%opts WMTS [width=600 height=400]
%%opts Points [tools=['hover'] ] (size=5.5)

url ='https://maps.wien.gv.at/basemap/bmapgrau/normal/google3857/{z}/{y}/{x}.png'
extents=(1795000,6075000,1818000,6090000)
geomap = gv.WMTS(WMTSTileSource(url=url), extents=extents, crs=crs.Mercator())
# location
baden = gv.Points((1807575,6108479),crs=crs.Mercator())

geomap * baden 
```
the point is about 35km to the north:
![image](https://user-images.githubusercontent.com/31547476/31884597-f144c4d0-b7ed-11e7-8042-f51e19b61098.png)

also, is there a way to  format the coordinates in meters (like axis.formatter from bokeh) or suppress the scientific coordinate notation (something like `np.set_printoptions(suppress=True)` )?

**Comment by philippjfr** [comment]
I'm seeing a lot of errors on the console with bokeh complaining about it not being able to load certain tiles. However if you use the crs.GOOGLE_MERCATOR projection it does appear to put it in the right place:

```
baden = gv.Points((1807575.65, 6108479.75), crs=crs.GOOGLE_MERCATOR)
```

<img width="683" alt="screen shot 2017-10-23 at 2 07 28 pm" src="https://user-images.githubusercontent.com/1550771/31890584-8a427ddc-b7fb-11e7-8700-3694757a56b9.png">

**Comment by philippjfr** [comment]
At the moment formatting the hover tool info isn't as straightforward as it should be. I'll try to provide an update once that changes (should be by the time of the next release).

**Comment by rr5577** [comment]
Thank you! Both the point and the raster image work now:
![image](https://user-images.githubusercontent.com/31547476/31891346-6abb1ae0-b806-11e7-9176-197a497744f7.png)

What i find a bit puzzling though is that they should be [both using the same parameters](https://gis.stackexchange.com/questions/40538/what-is-the-difference-between-epsg900913-and-epsg3857)?

Regarding the second question, i was trying to format the coordinate axes (from "6.085e+06" to "6085091", not the hover tool (though changing both would be ideal).

Thanks again for the help!

**Comment by philippjfr** [comment]
>Regarding the second question, i was trying to format the coordinate axes (from "6.085e+06" to "6085091", not the hover tool (which displays it in the desired format in the screenshot now, no idea why).

Ah, then you're in luck as you can see in my screenshot above we've now enabled a MercatorTicker on master, which will be included in the next release (hopefully later this week).

**Comment by philippjfr** [comment]
>What i find a bit puzzling though is that they should be both using the same parameters?

I don't think that's correct, I believe GOOGLE_MERCATOR clips the polar regions earlier.

**Comment by rr5577** [comment]
ah ok, that makes sense then.

one last question, 
`%%opts Points (alpha=0.2)` 
works nicely for the points, but not for the raster image. is there a different way to set image opacity? googling led me to [this](https://github.com/ioam/holoviews/issues/833), but that from over a year ago.

thanks again for being so helpful!

**Comment by philippjfr** [comment]
Unfortunately neither bokeh nor matplotlib currently support an alpha channel for colormapped images afaik. You could use the ``hv.operation.datashader.shade`` operation to colormap your image and then swap out the alpha channel, but that's quite a hassle. If I get a minute I might put together a small utility to do that.

**Comment by rr5577** [comment]
ah ok, hopefully it´ll be added at some point in the future?

> You could use the hv.operation.datashader.shade operation to colormap your image and then swap out the alpha channel
thanks, I can give that i try.

> If I get a minute I might put together a small utility to do that.
That´d be much appreciated of course, if you find the time.

**Comment by philippjfr** [comment]
This is a bit ugly but it works:

```python
from matplotlib.cm import get_cmap
from holoviews.operation.datashader import shade

def colormap_with_alpha(img, cmap='viridis', clims=None, alpha=1):
    cmap = get_cmap(cmap)
    arr = img.dimension_values(2, flat=False)
    coords = {d.name: img.dimension_values(d, False) for d in img.kdims}
    data = dict(coords, **{img.vdims[0].name: arr})
    shaded = shade(img.clone(data, datatype=['xarray']), cmap=cmap, clims=clims)
    data = dict(coords, **{vd.name: shaded.dimension_values(vd, flat=False) for vd in shaded.vdims[:4]})
    data['A'] = np.full_like(data['A'], int(alpha*255)) 
    return shaded.clone(data, vdims=['R', 'G', 'B', 'A'])

img = hv.Image(np.random.rand(10, 10))
colormap_with_alpha(img, alpha=0.2)
```

Will try to come up with a way to do it on the plot, I've got some ideas. Will close this issue now.

**Comment by rr5577** [comment]
that works great, thank you!

**Comment by Maurau** [comment]
Hi @philippjfr ,
your function colormap_with_alpha helped me a lot, thank you.
But it seems that using this function removes the colorbar in my final plot.
Do you have an idea how to modify this function to add a colorbar?
Thank you !
