### ISSUE TITLE
Quadmesh of geoviews Image overlay

### ISSUE THREAD

**Issue by suvarchal** [ioam/geoviews#99]
I like the holoviews Quadmesh of an Image as the hover tool works with it. 
But then when an Overlay of geoview Image and coastline is casted to Quadmesh, my jupyter notebook is stuck in the cell forever (atleast till an hour), i wish there was an error that i could report. 
one could reproduce this way i hope? or only me?
    

    import xarray as xr
    import holoviews as hv
    import geoviews as gv
    T_data=xr.tutorial.load_dataset('air_temperature')
    gT_data=gv.Dataset(T_data.isel(time=0))
    #this one works
    hv.QuadMesh(gv.Image(gT_data,kdims=['lon','lat']))(style={'tools':['hover']})
    #this gets stuck
    hv.Quadmesh(gv.Image(gT_data,kdims=['lon','lat'])*gv.feature.coastline)

**Comment by philippjfr** [comment]
I think you're just missing proper bracketing, what you were trying to do was casting an Overlay of the Image and the coastline to a QuadMesh, it should be:

```python
hv.Quadmesh(gv.Image(gT_data,kdims=['lon','lat'])) * gv.feature.coastline
```

That said you may run into issues with projections, you may need this:

```python
projected = gv.operation.project_image(gv.Image(gT_data,kdims=['lon','lat']))
hv.Quadmesh(projected) * gv.feature.coastline
```

**Comment by philippjfr** [comment]
Closing this, please reopen if you encounter further issues.

**Comment by suvarchal** [comment]
oh great!
`projected = gv.operation.project_image(gv.Image(gT_data,kdims=['lon','lat']))` did the trick, without it did not display the coastlines so i tried to do QuadMesh of Overlay. 

`
